server:
  port: 5001
  
spring:
  application:
    name: ruoyi-monitor
  profiles:
    active: dev
  #配置中心
  cloud:
    config:
      fail-fast: true
      name: ${spring.application.name}
      profile: ${spring.profiles.active}
      discovery:
        enabled: true
        service-id: ruoyi-config
        
# 注册中心配置
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址   
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'      
        