server: 
  port: 9527
 
spring: 
  application:
    name: ruoyi-zuul-gateway

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eureka7001.com:7001/eureka
       #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id:  ${spring.application.name}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址      
 
zuul: 
  ignored-services: "*"
  routes:
    system:
      serviceId: ruoyi-system
      path: /system/**
 

